services:
  - type: web
    name: freshclean-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_toko.py
    envVars:
      - key: PORT
        value: 10000
