services:
  - type: web
    name: freshclean-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_toko.py
    envVars:
      - key: PORT
        value: 10000
      - key: CUSTOMER_BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_PIN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
